spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
    pool:
      timeout: 1000
    lettuce:
      pool:
        max-active: 1500
        max-idle: 1000
        max-wait: 5000ms


server:
  port: 8083
